name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
          

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
             context: .
             push: true
             tags: akhilesh56/pipeline:${{ github.sha}}

      - name: Update Docker image on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            docker stop pipeline
            docker rm pipeline
            docker pull ${{secrets.DOCKER_USERNAME}}/pipeline:${{github.sha}}
            docker run -d --name pipeline -p 80:80 {{secrets.DOCKER_USERNAME}}/pipeline:${{github.sha}}
           