# name: Deploy to EC2

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1

#       - name: login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD}}
          

#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v2
#         with:
#              context: .
#              push: true
#              tags: akhilesh6956/pipeline:${{ github.sha}}  # dockerhub repository name akhilesh6956/-----

#       - name: Update Docker image on EC2 instance
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           command_timeout: 200m
#           script: |
              #docker pull ${{secrets.DOCKER_USERNAME}}/pipeline:${{github.sha}}
#             docker stop pipeline
#             docker rm pipeline
#             
#             docker run -d --name pipeline -p 80:80 {{secrets.DOCKER_USERNAME}}/pipeline:${{github.sha}}
name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
          

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
             context: .
             push: true
             tags: akhilesh6956/pipeline  # dockerhub repository name akhilesh6956/-----

      - name: Update Docker image on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            docker stop pipeline
            docker rm pipeline
            docker pull akhilesh6956/pipeline
            docker run -d --name pipeline -p 8000:8080 akhilesh6956/pipeline
        
           